#include "input_settings.h"

#include <windows.h>

#include <algorithm>
#include <fstream>
#include <sstream>
#include <system_error>

namespace t9ime {

namespace {

constexpr char kMarker[] = "# Generated by T9Ime settings";
constexpr char kStampFile[] = "t9ime.deployed";
const char* const kSchemas[] = {"t9", "rime_ice"};

std::string ReadText(const std::filesystem::path& p) {
  std::ifstream f(p, std::ios::binary);
  if (!f) return {};
  std::stringstream s;
  s << f.rdbuf();
  std::string t = s.str();
  t.erase(std::remove(t.begin(), t.end(), '\r'), t.end());
  return t;
}

bool WriteText(const std::filesystem::path& p, const std::string& text) {
  std::ofstream f(p, std::ios::binary | std::ios::trunc);
  f << text;
  return static_cast<bool>(f);
}

// The rules of `speller/algebra` in a schema file (comments and quotes as in
// the file; trailing " # comment" removed).
std::vector<std::string> SpellerAlgebra(const std::string& schema) {
  std::vector<std::string> rules;
  const size_t speller = schema.find("\nspeller:\n");
  if (speller == std::string::npos) return rules;
  const size_t algebra = schema.find("\n  algebra:\n", speller);
  if (algebra == std::string::npos) return rules;
  std::istringstream in(schema.substr(algebra + 12));
  std::string line;
  while (std::getline(in, line)) {
    if (line.empty()) continue;
    if (line.rfind("    ", 0) != 0) break;  // end of the list
    std::string item = line.substr(4);
    if (item.rfind("#", 0) == 0) continue;  // commented out
    if (item.rfind("- ", 0) != 0) break;
    item = item.substr(2);
    if (const size_t c = item.find(" #"); c != std::string::npos) item.resize(c);
    while (!item.empty() && item.back() == ' ') item.pop_back();
    rules.push_back(item);
  }
  return rules;
}

std::vector<std::string> FuzzyRules(const InputSettings& s) {
  std::vector<std::string> out;
  for (const FuzzyOption& o : FuzzyOptions()) {
    if (std::find(s.fuzzy.begin(), s.fuzzy.end(), o.id) == s.fuzzy.end()) continue;
    for (const char* r : o.rules) out.push_back(r);
  }
  return out;
}

// Size and write time of the shipped compiled data: changes with every upgrade.
std::string SharedIdentity(const std::filesystem::path& shared) {
  std::string id;
  for (const char* name : {"default.yaml", "t9.schema.yaml", "rime_ice.schema.yaml", "t9.prism.bin",
                           "rime_ice.table.bin"}) {
    std::error_code ec;
    const auto p = shared / "build" / name;
    const auto size = std::filesystem::file_size(p, ec);
    const auto time = std::filesystem::last_write_time(p, ec).time_since_epoch().count();
    id += std::string(name) + " " + std::to_string(ec ? 0 : size) + " " + std::to_string(ec ? 0 : time) + "\n";
  }
  return id;
}

std::string DeploymentStamp(const std::filesystem::path& shared, const std::filesystem::path& user) {
  std::string stamp = SharedIdentity(shared);
  for (const char* schema : kSchemas) stamp += ReadText(user / (std::string(schema) + ".custom.yaml"));
  return stamp;
}

bool IsGenerated(const std::filesystem::path& p) { return ReadText(p).rfind(kMarker, 0) == 0; }

}  // namespace

const std::vector<FuzzyOption>& FuzzyOptions() {
  static const std::vector<FuzzyOption> options = {
      {"z", L"z = zh", {"derive/^zh/z/", "derive/^z([^h])/zh$1/"}},
      {"c", L"c = ch", {"derive/^ch/c/", "derive/^c([^h])/ch$1/"}},
      {"s", L"s = sh", {"derive/^sh/s/", "derive/^s([^h])/sh$1/"}},
      {"nl", L"n = l", {"derive/^n/l/", "derive/^l/n/"}},
      {"fh", L"f = h", {"derive/^f/h/", "derive/^h/f/"}},
      {"rl", L"r = l", {"derive/^r/l/", "derive/^l/r/"}},
      {"an", L"an = ang", {"derive/ang$/an/", "derive/an$/ang/"}},
      {"en", L"en = eng", {"derive/eng$/en/", "derive/en$/eng/"}},
      {"in", L"in = ing", {"derive/ing$/in/", "derive/in$/ing/"}},
      {"ian", L"ian = iang", {"derive/iang$/ian/", "derive/ian$/iang/"}},
      {"uan", L"uan = uang", {"derive/uang$/uan/", "derive/uan$/uang/"}},
  };
  return options;
}

InputSettings LoadInputSettings(const std::wstring& ini) {
  InputSettings s;
  if (ini.empty()) return s;
  s.traditional = GetPrivateProfileIntW(L"input", L"traditional", 0, ini.c_str()) != 0;
  s.page_size = std::clamp(static_cast<int>(GetPrivateProfileIntW(L"input", L"page_size", 5, ini.c_str())),
                           kMinPageSize, kMaxPageSize);
  wchar_t buf[256] = {};
  GetPrivateProfileStringW(L"input", L"fuzzy", L"", buf, 256, ini.c_str());
  const std::wstring list = std::wstring(L",") + buf + L",";
  for (const FuzzyOption& o : FuzzyOptions()) {
    const std::string id = o.id;
    if (list.find(L"," + std::wstring(id.begin(), id.end()) + L",") != std::wstring::npos) s.fuzzy.push_back(o.id);
  }
  return s;
}

void SaveInputSettings(const std::wstring& ini, const InputSettings& s) {
  if (ini.empty()) return;
  WritePrivateProfileStringW(L"input", L"traditional", s.traditional ? L"1" : L"0", ini.c_str());
  WritePrivateProfileStringW(L"input", L"page_size", std::to_wstring(s.page_size).c_str(), ini.c_str());
  std::wstring list;
  for (const std::string& id : s.fuzzy) list += (list.empty() ? L"" : L",") + std::wstring(id.begin(), id.end());
  WritePrivateProfileStringW(L"input", L"fuzzy", list.c_str(), ini.c_str());
}

std::string GenerateCustomization(const std::filesystem::path& shared, const std::string& schema,
                                  const InputSettings& s) {
  const std::vector<std::string> fuzzy = FuzzyRules(s);
  const bool page = schema == "rime_ice" && s.page_size != InputSettings{}.page_size;
  if (fuzzy.empty() && !page) return {};

  std::string base = ReadText(shared / (schema + ".custom.yaml"));
  if (base.find("\npatch:") == std::string::npos && base.rfind("patch:", 0) != 0) base += "patch:\n";
  while (!base.empty() && base.back() == '\n') base.pop_back();
  std::string out = std::string(kMarker) + " (shipped patch + settings); do not edit, it is regenerated.\n" + base +
                    "\n";
  if (!fuzzy.empty()) {
    std::vector<std::string> rules = SpellerAlgebra(ReadText(shared / (schema + ".schema.yaml")));
    // Fuzzy rules act on letters: before the nine-key digit mapping, or first.
    auto at = rules.begin();
    if (schema == "t9") {
      at = std::find_if(rules.begin(), rules.end(), [](const std::string& r) { return r.rfind("derive/[abc]/2/", 0) == 0; });
    }
    rules.insert(at, fuzzy.begin(), fuzzy.end());
    out += "  speller/algebra:\n";
    for (const std::string& r : rules) out += "    - " + r + "\n";
  }
  if (page) out += "  menu/page_size: " + std::to_string(s.page_size) + "\n";
  return out;
}

bool PrepareUserData(const std::filesystem::path& shared, const std::filesystem::path& user, const InputSettings& s) {
  std::error_code ec;
  std::filesystem::create_directories(user, ec);
  bool customized = false;
  for (const char* schema : kSchemas) {
    const auto file = user / (std::string(schema) + ".custom.yaml");
    const std::string text = GenerateCustomization(shared, schema, s);
    if (!text.empty()) {
      customized = true;
      if (ReadText(file) != text) WriteText(file, text);
    } else if (IsGenerated(file)) {
      std::filesystem::remove(file, ec);  // defaults again: the shipped patch applies
    }
  }
  const auto build = user / "build";
  const bool has_build = std::filesystem::exists(build, ec);
  if (!customized) {
    // Compiled data from earlier settings would hide the shipped data (also
    // after an upgrade): the pre-deployed data is used directly.
    if (has_build) std::filesystem::remove_all(build, ec);
    std::filesystem::remove(user / kStampFile, ec);
    return false;
  }
  return !has_build || ReadText(user / kStampFile) != DeploymentStamp(shared, user);
}

void MarkDeployed(const std::filesystem::path& shared, const std::filesystem::path& user) {
  WriteText(user / kStampFile, DeploymentStamp(shared, user));
}

}  // namespace t9ime
