"""Generate the T9 syllable table from rime-ice's single-character dictionary.

Every pinyin syllable that appears in cn_dicts/8105.dict.yaml is emitted with its
nine-key digit code and a frequency (sum of the weights of all characters read
with that syllable). Output is a C++ include consumed by syllable_index.cpp.

Usage: gen_syllables.py --dict <8105.dict.yaml> --out <syllable_table.gen.inc>
"""
import argparse
import re
from collections import defaultdict
from pathlib import Path

KEYS = {
    **dict.fromkeys('abc', '2'), **dict.fromkeys('def', '3'),
    **dict.fromkeys('ghi', '4'), **dict.fromkeys('jkl', '5'),
    **dict.fromkeys('mno', '6'), **dict.fromkeys('pqrs', '7'),
    **dict.fromkeys('tuv', '8'), **dict.fromkeys('wxyz', '9'),
}
SYLLABLE = re.compile(r'^[a-z]+$')


def to_digits(syllable: str) -> str:
    return ''.join(KEYS[c] for c in syllable)


def read_syllables(dict_path: Path) -> dict[str, int]:
    freq: dict[str, int] = defaultdict(int)
    in_body = False
    for raw in dict_path.read_text(encoding='utf-8').splitlines():
        if not in_body:
            in_body = raw.strip() == '...'
            continue
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        cols = line.split('\t')
        if len(cols) < 2:
            continue
        for syllable in cols[1].split():
            if SYLLABLE.match(syllable):
                weight = int(cols[2]) if len(cols) > 2 and cols[2].isdigit() else 0
                freq[syllable] += weight
    if not freq:
        raise SystemExit(f'no syllables found in {dict_path}')
    return freq


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--dict', required=True, type=Path)
    ap.add_argument('--out', required=True, type=Path)
    args = ap.parse_args()

    freq = read_syllables(args.dict)
    rows = sorted(freq.items(), key=lambda kv: (to_digits(kv[0]), -kv[1], kv[0]))
    lines = [
        '// Generated by tools/gen_syllables/gen_syllables.py -- do not edit.',
        f'// Source: {args.dict.name}, {len(rows)} syllables.',
        '// { spelling, digits, frequency }',
    ]
    lines += [f'{{"{s}", "{to_digits(s)}", {f}u}},' for s, f in rows]
    text = '\n'.join(lines) + '\n'
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if not args.out.exists() or args.out.read_text(encoding='utf-8') != text:
        args.out.write_text(text, encoding='utf-8')


if __name__ == '__main__':
    main()
